[build]
buildCommand = "python manage.py collectstatic --noinput"

[deploy]
startCommand = "python manage.py migrate --noinput && gunicorn config.wsgi --pythonpath src --bind 0.0.0.0:$PORT --workers 3 --threads 2"
